export const tables = {
  animations: 'elsewherequests_animations',
  attributes: 'elsewherequests_attributes',
  gatherObjectiveItems: 'elsewherequests_gatherobjective_items',
  gatherObjectives: 'elsewherequests_gatherobjectives',
  itemPrimaryAttributes: 'elsewherequests_',
  itemSecondaryAttributes: 'elsewherequests_',
  itemRewards: 'elsewherequests_itemrewards',
  items: 'elsewherequests_items',
  killObjectives: 'elsewherequests_killobjectives',
  killObjectiveMobs: 'elsewherequests_killobjective_mobs',
  mobAttributes: 'elsewherequests_mob_attributes',
  mobs: 'elsewherequests_mobs',
  mods: 'elsewherequests_mods',
  names: 'elsewherequests_names',
  questGiverNames: 'elsewherequests_questgiver_names',
  questGiverQuests: 'elsewherequests_questgiver_quests',
  questGivers: 'elsewherequests_questgivers',
  quests: 'elsewherequests_quests',
  shapeAnimations: 'elsewherequests_shape_animations',
  shapeTextureSubTypes: 'elsewherequests_shapetexture_subtypes',
  shapeTextureAlts: 'elsewherequests_shape_texturealts',
  shapes: 'elsewherequests_shapes',
  subTypes: 'elsewherequests_subtypes',
  textureAlts: 'elsewherequests_texturealts'
}